// ==UserScript==
// @name         Translate GM
// @version      0.3
// @description  Translate GM
// @author		 Phost
// @updateURL	 https://github.com/2phost/mh-gh-translator/raw/main/translate_gm.user.js
// @downloadURL  https://github.com/2phost/mh-gh-translator/raw/main/translate_gm.user.js
// @match        https://gest-hordes2.eragaming.fr/*
// @grant        none
// ==/UserScript==

(function() {
    var replaceArry = [
		[/Carte/gi, "Map"],
		[/Sauvegarder/gi, "Save"],
        [/Plans de chantiers/gi, "Blueprints"],
        [/Plans de chantier/gi, "Blueprints"],
        [/Mise à jour/gi, "Update"],
        [/Ville/gi, "Town"],
        [/Citoyens/gi, 'Citizens'],
        [/Bâtiments/gi, 'Ruins'],
		[/Douves/gi, "Great Moat"],
        [/Grand Fossé/gi, "Great Pit"],
        [/Le Grand fossé apporte 23 points de défense./gi, "The Great Pit gives an additional 23 defence points."],
        [/Le Grand fossé apporte 44 points de défense./gi, "The Great Pit gives an additional 44 defence points."],
        [/Le Grand fossé apporte 76 points de défense./gi, "The Great Pit gives an additional 76 defence points."],
        [/Le Grand fossé apporte 109 points de défense./gi, "The Great Pit gives an additional 109 defence points."],
        [/Le Grand fossé apporte 160 points de défense./gi, "The Great Pit gives an additional 160 defence points."],
        [/Muraille rasoir/gi, "Grater"],
        [/Fosse à Pieux/gi, "Spiked Pit"],
        [/Appâts/gi, "Bait"],
        [/Barbelés/gi, "Barbed Wire"],
        [/Remparts avancés/gi, "Wall Upgrade v2"],
        [/Grogro mur/gi, "Überwall"],
        [/Muraille à pointes/gi, "Spiked Wall"],
        [/Troisième couche/gi, "Third Wall"],
        [/Seconde couche/gi, "Inner Wall"],
        [/Bétonnade/gi, "Concrete Reinforcement"],
        [/Muraille évolutive/gi, "Evolutive Wall"],
        [/La Muraille évolutive apporte 85 points de défense./gi, "The Evolutive Wall gives an additional 85 defence points."],
        [/La Muraille évolutive apporte 120 points de défense./gi, "The Evolutive Wall gives an additional 120 defence points."],
        [/La Muraille évolutive apporte 170 points de défense./gi, "The Evolutive Wall gives an additional 170 defence points."],
        [/La Muraille évolutive apporte 235 points de défense./gi, "The Evolutive Wall gives an additional 235 defence points."],
        [/La Muraille évolutive apporte 315 points de défense./gi, "The Evolutive Wall gives an additional 315 defence points."],
        [/Poutres renfort/gi, "Metal Patches"],
        [/Râpe à zombies/gi, "Zombie Grater"],
        [/Oubliettes/gi, "Old-school traps"],
        [/Palissade/gi, "Small Fence"],
        [/Contre-plaqué/gi, "Plywood"],
        [/Cloison épaisse/gi, "Armour Plating v3"],
        [/Bastion/gi, "Extrawall"],
        [/Cloison en bois/gi, "Armour Plating"],
        [/Cloison métallique/gi, "Armour Plating v2"],
        [/Mur Savonné/gi, "Slip 'n' Slide"],
        [/Neurotoxine/gi, "Gas Gun"],
        [/Projection acide/gi, "Acid Spray"],
        [/Pulvérisateur/gi, "Vaporiser"],
        [/Muraille/gi, "Wall Upgrade v1"],
        [/Champ mines eau/gi, "Mines"],
        [/Filtre/gi, "Water Filter"],
        [/Purificateur/gi, "Water Purifier"],
        [/Fertilisation sauvage/gi, "Fertilizer"],
        [/Pamplemousses explosifs/gi, "Grapeboom"],
        [/Potager/gi, "Vegetable Plot"],
        [/Projet Eden/gi, "Eden Project"],
        [/Foreuse puits/gi, "Drilling Rig"],
        [/Vaporisateur/gi, "Boiling Fog"],
        [/Sanibroyeur/gi, "Saniflow Macerator"],
        [/Arroseurs auto/gi, "Automatic Sprinkler"],
        [/Douches/gi, "Shower"],
        [/Réseau hydraulique/gi, "Hydraulic Network"],
        [/Aqua tourelles/gi, "Water Turrets"],
        [/Percée/gi, "Water Catcher"],
        [/Pluvio-canons/gi, "Mist Spray"],
        [/Caniveaux/gi, "Sluice"],
        [/Rid'eau/gi, "Decon Shower"],
        [/Roquette Foreuse/gi, "Divining Rocket"],
        [/Détecteur à eau/gi, "Divining Rods"],
        [/Pommier de l'Outre-Monde/gi, "Apple Tree"],
        [/Pompe/gi, "Pump"],
        [/Ajoute 20 Rations d'eau dans le puits (une seule fois)./gi, "Add 20 water rations to the well (one time only)."],
        [/Ajoute 30 Rations d'eau dans le puits (une seule fois)./gi, "Add 30 water rations to the well (one time only)."],
        [/Ajoute 40 Rations d'eau dans le puits (une seule fois)./gi, "Add 40 water rations to the well (one time only)."],
        [/Crémato-Cue/gi, "Cremato-Cue"],
        [/Boucherie/gi, "Butcher"],
        [/Fixations de défenses/gi, "Defensive Focus"],
        [/Canon à briques/gi, "Rock Cannon"],
        [/Perforeuse/gi, "Railgun"],
        [/Lance-Grenailles/gi, "Plate Gun"],
        [/Canon brutal/gi, "Brutal Cannon"],
        [/Monticules canons/gi, "Cannon Mounds"],
        [/Tourniquet/gi, "War Mill"],
        [/Manufacture/gi, "Factory"],
        [/Scies hurlantes/gi, "Screaming Saws"],
        [/Architectoire/gi, "Architect’s Study"],
        [/La ville obtiendra 4 plans communs après l'attaque./gi, "The Town will receive 4 common blueprints after the attack."],
        [/Registre chantier/gi, "Building Registry"],
        [/Potence/gi, "Gallows"],
        [/Cantine à bois/gi, "Small Café"],
        [/Cercueils sur ressort/gi, "Coffin Catapult"],
        [/Cimetière cadenassé/gi, "Small Cemetary"],
        [/Poulailler/gi, "Henhouse"],
        [/Abattoir/gi, "Abbatoir"],
        [/Supports défensifs/gi, "Defensive Thinktank"],
        [/Cantine centrale/gi, "Central Cafeteria"],
        [/Quartiers circulaires/gi, "Community Involvement"],
        [/Stratégies citoyennes/gi, "Builder’s Merchant"],
        [/Infirmerie/gi, "Infirmary"],
        [/Laboratoire central/gi, "Central Laboratory"],
        [/Atelier/gi, "Workshop"],
        [/Le coût en PA de tous les chantiers est réduit de 6%./gi, "The cost (AP) of all construction projects is reduced by 6%."],
        [/Le coût en PA de tous les chantiers est réduit de 12%./gi, "The cost (AP) of all construction projects is reduced by 12%."],
        [/Le coût en PA de tous les chantiers est réduit de 18%./gi, "The cost (AP) of all construction projects is reduced by 18%."],
        [/Scanner/gi, "Scanner"],
        [/Carte améliorée/gi, "Upgraded Map"],
        [/Planificateur/gi, "Predictor"],
        [/Scrutateur/gi, "Searchtower"],
        [/Les chances de régénération d'une case du désert passent à 37%./gi, "There is a 37% chance of desert zone regeneration."],
        [/Les chances de régénération d'une case du désert passent à 49%./gi, "There is a 49% chance of desert zone regeneration."],
        [/Les chances de régénération d'une case du désert passent à 61%./gi, "There is a 61% chance of desert zone regeneration."],
        [/Les chances de régénération d'une case du désert passent à 73%./gi, "There is a 73% chance of desert zone regeneration."],
        [/Les chances de régénération d'une case du désert passent à 85%./gi, "There is a 85% chance of desert zone regeneration."],
        [/Champs piégés/gi, "Spikes"],
        [/Renforts d'urgence/gi, "Wood Plating"],
        [/Guérilla/gi, "Guerilla Traps"],
        [/Mont pointu/gi, "Mount Killaman-Jaro"],
        [/Tas détritus/gi, "Rubbish Heap"],
        [/Piège à loups/gi, "Pits"],
        [/Dynamitage/gi, "Bomb Factory"],
        [/Panique/gi, "Abject Panic"],
        [/La Bamba/gi, "Frat House"],
        [/Pluie bénite/gi, "Holy Raincloud"],
        [/Poupée Vaudou XXL/gi, "XXL Voodoo Doll"],
        [/Mirage Spirituel/gi, "Spirit Mirage"],
        [/Guillotine à Bokor/gi, "Sword of Bokor"],
        [/Dispositifs d'urgence/gi, "Emergency Supplies"],
        [/Catapulte calibrée/gi, "Upgraded Catapult"],
        [/Catapulte Primitive/gi, "Catapult"],
        [/Armurerie/gi, "Miniature Armory"],
        [/Magasin suédois/gi, "Swedish Workshop"],
        [/Tourelle lance-eau/gi, "Shooting Gallery"],
        [/Lance-bête/gi, "Small Trebuchet"],
        [/Tour des gardiens/gi, "Guard Tower"],
        [/Tour des éclaireurs/gi, "Crows’ Nest"],
        [/Tour de guet/gi, "Watchtower"],
        [/Chaque matin, détecte tous les zombies à 3 km de la ville./gi, "Zombies within 3 zones are detected."],
        [/Chaque matin, détecte tous les zombies à 6 km de la ville./gi, "Zombies within 6 zones are detected."],
        [/Chaque matin, détecte tous les zombies à 10 km de la ville./gi, "Zombies within 10 zones are detected."],
        [/Derrick/gi, "Mechanical Pump"],
        [/Fausse Ville/gi, "False Town"],
        [/Robinetterie/gi, "Faucet"],
        [/Grand déménagement/gi, "The Big Rebuild"],
        [/Champs d'épouvantails/gi, "Scarecrows"],
        [/Cage à viande/gi, "Meat Locker"],
        [/Dictature des héros/gi, "People’s Court"],
        [/Habitations fortifiées/gi, "Fortifications"],
        [/Déchardes de bois/gi, "Wood Dump"],
        [/Ferraillerie/gi, "Metal Dump"],
        [/Enclos/gi, "Animal Dump"],
        [/Décharge organisée/gi, "Free Dump"],
        [/Décharge piégée/gi, "Weapons Dump"],
        [/Appâts odorants/gi, "Food Dump"],
        [/Décharge blindée/gi, "Defence Dump"],
        [/Décharge humidifiée/gi, "Dump Upgrade"],
        [/Décharge publique/gi, "Garbage Dump"],
        [/Phare/gi, "Lighthouse"],
        [/Autel de la rédemption/gi, "Altar"],
        [/Château de sable/gi, "Giant Sandcastle"],
        [/Feu de joie/gi, "Bonfire"],
        [/Bureau des esclavagistes/gi, "Ministry of Slavery"],
        [/Réacteur soviétique/gi, "Reactor"],
        [/Labyrinthe/gi, "Labyrinth"],
        [/Dernière chance/gi, "All or Nothing"],
        [/PMV géant/gi, "Giant BRD"],
        [/Grande roue de Grostas/gi, "Wonder Wheel"],
        [/Feux d'artifices/gi, "Firework Foray"],
        [/Statue du Corbeau/gi, "Crow Statue"],
        [/Cinéma/gi, "Cinema"],
        [/Roquettes/gi, "Air Strike"],
        [/Montgolfière/gi, "Hot Air Balloon"],
        [/Foreuse améliorée/gi, "No Holes Barred"],
        [/Fondations/gi, "Foundations"],
        [/Blindage d'entrée/gi, "Reinforced Gates"],
        [/Piston calibré/gi, "Last-Minute Lock"],
        [/Piston verrou/gi, "Automatic Piston Lock"],
        [/Conduite d'aération/gi, "Ventilation System"],
        [/Portail/gi, "Portal Lock"],
        [/Lit de camp/gi, "Camp Bed"],
        [/Tente/gi, "Tent"],
        [/Taudis/gi, "Hovel"],
        [/Baraque/gi, "Shack"],
        [/Maison/gi, "House"],
        [/Maison clôturée/gi, "Safehouse"],
        [/Abri fortifié/gi, "Stronghold"],
        [/Bunker/gi, "Nuclear Bunker"],
        [/Château/gi, "Palace"],
        [/Gros rideau/gi, "Large Curtain"],
        [/Cave laboratoire/gi, "Home Laboratory"],
        [/Cuisine/gi, "Kitchen"],
        [/Alarme rudimentaire/gi, "Rudimentary Alarm"],
        [/Coin sieste/gi, "Siesta Time™"],
        [/Verrou/gi, "Lock"],
        [/Rangements/gi, "More Storage"],
        [/Renforts/gi, "Reinforcements"],
        [/en défense/gi, "Defence"],
        [/Chemin de ronde/gi, "Battlements"],
        [/Hamâme/gi, "Hammam"],
        [/Construction temporaire !/gi, "Temporary Building!"],
        [/Vous pourrez de nouveau la bâtir demain si vous le souhaitez./gi, "You can build it again tomorrow if you wish."],
        [/Augmente sensiblement les défenses de la ville./gi, "Significantly increases the town's defences."],
        [/Une amélioration du Grand Fossé, y mettre de l'eau…/gi, "Another upgrade for the Great Pit: fill it with water..."],
        [/Des structures métalliques pour renforcer les parties faibles de la muraille./gi, "Metallic supports to reinforce the weaker parts of the wall."],
        [/Accroît significativement le rendement du Potager./gi, "Significantly increases the yield of the vegetable plot."],
        [/De la dynamite, des zombies, du sang./gi, "Dynamite, Zombies, Blood."],
        [/Permet la destruction de bois dans la décharge./gi, "Allows the destruction of wood at the dump."],
        [/Permet la destruction de métal dans la décharge./gi, "Allows the destruction of metal at the dump."],
        [/Permet la destruction d'armes dans la décharge./gi, "Allows the destruction of weapons at the dump."],
        [/Permet la destruction de nourriture dans la décharge./gi, "Allows the destruction of food at the dump."],
        [/Permet le massacre d'animaux innocents dans la décharge./gi, "Allows the massacre of innocent animals at the dump."],
        [/La porte se referme automatiquement à 23h59 au lieu de 23h30./gi, "The gates close automatically at 22h59 instead of 22h30.."],
        [/L'organisation de la défense est optimisée, le gain de la défense total de la ville passe à 12%./gi, "The total defence of the town is permanently increased by 12%."],
        [/L'organisation de la défense atteint son niveau maximum, le gain de la défense total de la ville passe à 14%./gi, "The total defence of the town is permanently increased by 14%."],
        [/Barrières/gi, "Wooden Fencing"],
        [/Clôture/gi, "Fence"],
        [/Croix en Chocolat/gi, "Chocolate Cross"],
        [/Éclairage public/gi, "Public lights"],
        [/Aucun bonus spécial/gi, "No special bonus"],
        [/L'organisation de la défense est basique, le gain de la défense total de la ville passe à 10%./gi, "The total defence of the town is permanently increased by 10%."],
        [/Le Grand fossé apporte 10 points de défense./gi, "The Great Pit gives an additional 10 defence points."],
        [/La Muraille évolutive apporte 55 points de défense./gi, "The upgraded great wall gives an additional 55 defence points."],
        [/Ajoute 5 rations d'eau dans le puits (une seule fois)./gi, "5 rations of water are added to the well (one time only)"],
        [/La ville obtiendra 1 plan commun après l'attaque./gi, "The Town will receive 1 common blueprints after the atta
    ];
    var numTerms = replaceArry.length;
    var txtWalker = document.createTreeWalker (
        document.body,
        NodeFilter.SHOW_TEXT,
        {acceptNode: function (node) {
            //-- Skip whitespace-only nodes
            if (node.nodeValue.trim()){
                return NodeFilter.FILTER_ACCEPT;
            }

            return NodeFilter.FILTER_SKIP;
        }
        },
        false
    );
    var txtNode = null;

    while (txtNode = txtWalker.nextNode () ) {
        var oldTxt = txtNode.nodeValue;

        for (var J = 0; J < numTerms; J++) {
            oldTxt = oldTxt.replace (replaceArry[J][0], replaceArry[J][1]);
        }
        txtNode.nodeValue = oldTxt;
    }
})();
