// ==UserScript==
// @name         Translate GM
// @version      0.4
// @description  Translate GM
// @author		 Phost
// @updateURL	 https://github.com/2phost/mh-gh-translator/raw/main/translate_gm.user.js
// @downloadURL  https://github.com/2phost/mh-gh-translator/raw/main/translate_gm.user.js
// @match        https://gest-hordes2.eragaming.fr/*
// @grant        none
// ==/UserScript==

(function() {
    var replaceArry = [
		[/Douves/gi, "Great Moat"],
        [/Grand Fossé/gi, "Great Pit"],
        [/Muraille rasoir/gi, "Grater"],
        [/Fosse à Pieux/gi, "Spiked Pit"],
        [/Appâts/gi, "Bait"],
        [/Barbelés/gi, "Barbed Wire"],
        [/Remparts avancés/gi, "Wall Upgrade v2"],
        [/Grogro mur/gi, "Überwall"],
        [/Muraille à pointes/gi, "Spiked Wall"],
        [/Troisième couche/gi, "Third Wall"],
        [/Seconde couche/gi, "Inner Wall"],
        [/Bétonnade/gi, "Concrete Reinforcement"],
        [/Muraille évolutive/gi, "Evolutive Wall"],
        [/Poutres renfort/gi, "Metal Patches"],
        [/Râpe à zombies/gi, "Zombie Grater"],
        [/Oubliettes/gi, "Old-school traps"],
        [/Palissade/gi, "Small Fence"],
        [/Contre-plaqué/gi, "Plywood"],
        [/Cloison épaisse/gi, "Armour Plating v3"],
        [/Bastion/gi, "Extrawall"],
        [/Cloison en bois/gi, "Armour Plating"],
        [/Cloison métallique/gi, "Armour Plating v2"],
        [/Mur Savonné/gi, "Slip 'n' Slide"],
        [/Neurotoxine/gi, "Gas Gun"],
        [/Projection acide/gi, "Acid Spray"],
        [/Pulvérisateur/gi, "Vaporiser"],
        [/Muraille/gi, "Wall Upgrade v1"],
        [/Champ mines eau/gi, "Mines"],
        [/Filtre/gi, "Water Filter"],
        [/Purificateur/gi, "Water Purifier"],
        [/Fertilisation sauvage/gi, "Fertilizer"],
        [/Pamplemousses explosifs/gi, "Grapeboom"],
        [/Potager/gi, "Vegetable Plot"],
        [/Projet Eden/gi, "Eden Project"],
        [/Foreuse puits/gi, "Drilling Rig"],
        [/Vaporisateur/gi, "Boiling Fog"],
        [/Sanibroyeur/gi, "Saniflow Macerator"],
        [/Arroseurs auto/gi, "Automatic Sprinkler"],
        [/Douches/gi, "Shower"],
        [/Réseau hydraulique/gi, "Hydraulic Network"],
        [/Aqua tourelles/gi, "Water Turrets"],
        [/Percée/gi, "Water Catcher"],
        [/Pluvio-canons/gi, "Mist Spray"],
        [/Caniveaux/gi, "Sluice"],
        [/Rid'eau/gi, "Decon Shower"],
        [/Roquette Foreuse/gi, "Divining Rocket"],
        [/Détecteur à eau/gi, "Divining Rods"],
        [/Pommier de l'Outre-Monde/gi, "Apple Tree"],
        [/Pompe/gi, "Pump"],
        [/Crémato-Cue/gi, "Cremato-Cue"],
        [/Boucherie/gi, "Butcher"],
        [/Fixations de défenses/gi, "Defensive Focus"],
        [/Canon à briques/gi, "Rock Cannon"],
        [/Perforeuse/gi, "Railgun"],
        [/Lance-Grenailles/gi, "Plate Gun"],
        [/Canon brutal/gi, "Brutal Cannon"],
        [/Monticules canons/gi, "Cannon Mounds"],
        [/Tourniquet/gi, "War Mill"],
        [/Manufacture/gi, "Factory"],
        [/Scies hurlantes/gi, "Screaming Saws"],
        [/Architectoire/gi, "Architect’s Study"],
        [/Registre chantier/gi, "Building Registry"],
        [/Potence/gi, "Gallows"],
        [/Cantine à bois/gi, "Small Café"],
        [/Cercueils sur ressort/gi, "Coffin Catapult"],
        [/Cimetière cadenassé/gi, "Small Cemetary"],
        [/Poulailler/gi, "Henhouse"],
        [/Abattoir/gi, "Abbatoir"],
        [/Supports défensifs/gi, "Defensive Thinktank"],
        [/Cantine centrale/gi, "Central Cafeteria"],
        [/Quartiers circulaires/gi, "Community Involvement"],
        [/Stratégies citoyennes/gi, "Builder’s Merchant"],
        [/Infirmerie/gi, "Infirmary"],
        [/Laboratoire central/gi, "Central Laboratory"],
        [/Atelier/gi, "Workshop"],
        [/Scanner/gi, "Scanner"],
        [/Carte améliorée/gi, "Upgraded Map"],
        [/Planificateur/gi, "Predictor"],
        [/Scrutateur/gi, "Searchtower"],
        [/Champs piégés/gi, "Spikes"],
        [/Renforts d'urgence/gi, "Wood Plating"],
        [/Guérilla/gi, "Guerilla Traps"],
        [/Mont pointu/gi, "Mount Killaman-Jaro"],
        [/Tas détritus/gi, "Rubbish Heap"],
        [/Piège à loups/gi, "Pits"],
        [/Dynamitage/gi, "Bomb Factory"],
        [/Panique/gi, "Abject Panic"],
        [/La Bamba/gi, "Frat House"],
        [/Pluie bénite/gi, "Holy Raincloud"],
        [/Poupée Vaudou XXL/gi, "XXL Voodoo Doll"],
        [/Mirage Spirituel/gi, "Spirit Mirage"],
        [/Guillotine à Bokor/gi, "Sword of Bokor"],
        [/Dispositifs d'urgence/gi, "Emergency Supplies"],
        [/Catapulte calibrée/gi, "Upgraded Catapult"],
        [/Catapulte Primitive/gi, "Catapult"],
        [/Armurerie/gi, "Miniature Armory"],
        [/Magasin suédois/gi, "Swedish Workshop"],
        [/Tourelle lance-eau/gi, "Shooting Gallery"],
        [/Lance-bête/gi, "Small Trebuchet"],
        [/Tour des gardiens/gi, "Guard Tower"],
        [/Tour des éclaireurs/gi, "Crows’ Nest"],
        [/Tour de guet/gi, "Watchtower"],
        [/Derrick/gi, "Mechanical Pump"],
        [/Fausse Ville/gi, "False Town"],
        [/Robinetterie/gi, "Faucet"],
        [/Grand déménagement/gi, "The Big Rebuild"],
        [/Champs d'épouvantails/gi, "Scarecrows"],
        [/Cage à viande/gi, "Meat Locker"],
        [/Dictature des héros/gi, "People’s Court"],
        [/Habitations fortifiées/gi, "Fortifications"],
        [/Déchardes de bois/gi, "Wood Dump"],
        [/Ferraillerie/gi, "Metal Dump"],
        [/Enclos/gi, "Animal Dump"],
        [/Décharge organisée/gi, "Free Dump"],
        [/Décharge piégée/gi, "Weapons Dump"],
        [/Appâts odorants/gi, "Food Dump"],
        [/Décharge blindée/gi, "Defence Dump"],
        [/Décharge humidifiée/gi, "Dump Upgrade"],
        [/Décharge publique/gi, "Garbage Dump"],
        [/Phare/gi, "Lighthouse"],
        [/Autel de la rédemption/gi, "Altar"],
        [/Château de sable/gi, "Giant Sandcastle"],
        [/Feu de joie/gi, "Bonfire"],
        [/Bureau des esclavagistes/gi, "Ministry of Slavery"],
        [/Réacteur soviétique/gi, "Reactor"],
        [/Labyrinthe/gi, "Labyrinth"],
        [/Dernière chance/gi, "All or Nothing"],
        [/PMV géant/gi, "Giant BRD"],
        [/Grande roue de Grostas/gi, "Wonder Wheel"],
        [/Feux d'artifices/gi, "Firework Foray"],
        [/Statue du Corbeau/gi, "Crow Statue"],
        [/Cinéma/gi, "Cinema"],
        [/Roquettes/gi, "Air Strike"],
        [/Montgolfière/gi, "Hot Air Balloon"],
        [/Foreuse améliorée/gi, "No Holes Barred"],
        [/Fondations/gi, "Foundations"],
        [/Blindage d'entrée/gi, "Reinforced Gates"],
        [/Piston calibré/gi, "Last-Minute Lock"],
        [/Piston verrou/gi, "Automatic Piston Lock"],
        [/Conduite d'aération/gi, "Ventilation System"],
        [/Portail/gi, "Portal Lock"],
        [/Lit de camp/gi, "Camp Bed"],
        [/Tente/gi, "Tent"],
        [/Taudis/gi, "Hovel"],
        [/Baraque/gi, "Shack"],
        [/Maison/gi, "House"],
        [/Maison clôturée/gi, "Safehouse"],
        [/Abri fortifié/gi, "Stronghold"],
        [/Bunker/gi, "Nuclear Bunker"],
        [/Château/gi, "Palace"],
        [/Gros rideau/gi, "Large Curtain"],
        [/Cave laboratoire/gi, "Home Laboratory"],
        [/Cuisine/gi, "Kitchen"],
        [/Alarme rudimentaire/gi, "Rudimentary Alarm"],
        [/Coin sieste/gi, "Siesta Time™"],
        [/Verrou/gi, "Lock"],
        [/Rangements/gi, "More Storage"],
        [/Renforts/gi, "Reinforcements"],
        [/en défense/gi, "Defence"],
        [/Chemin de ronde/gi, "Battlements"],
        [/Hamâme/gi, "Hammam"],
        [/Construction temporaire !/gi, "Temporary Building!"],
        [/Barrières/gi, "Wooden Fencing"],
        [/Clôture/gi, "Fence"],
        [/Croix en Chocolat/gi, "Chocolate Cross"],
        [/Eclairage public/gi, "Public lights"],
        [/Hôpital abandonné/gi, "Abandonned Hospital"],
        [/Nuclear Bunker abandonné/gi, "Abandoned Hotel"],
        [/Nuclear Bunker abandonné/gi, "Abandoned Bunker"],
		[/Carte/gi, "Map"],
		[/Sauvegarder/gi, "Save"],
		[/Annuler modification/gi, "Cancel"],
		[/Vous êtes actuellement dans la/gi, "You are currently in the"],
        [/Plans de chantiers dans les ruines/gi, "ERuin Blueprints"],
        [/Plans de chantiers/gi, "Blueprints"],
        [/Plans de chantier/gi, "Blueprints"],
        [/Mise à jour/gi, "Update"],
        [/Mis à jour par/gi, "Updated by"],
        [/Ville/gi, "Town"],
        [/Citoyens/gi, 'Citizens'],
        [/Bâtiments/gi, 'Ruins'],
        [/jour/gi, 'day'],
    ];
    var numTerms = replaceArry.length;
    var txtWalker = document.createTreeWalker (
        document.body,
        NodeFilter.SHOW_TEXT,
        {acceptNode: function (node) {
            //-- Skip whitespace-only nodes
            if (node.nodeValue.trim()){
                return NodeFilter.FILTER_ACCEPT;
            }

            return NodeFilter.FILTER_SKIP;
        }
        },
        false
    );
    var txtNode = null;

    while (txtNode = txtWalker.nextNode () ) {
        var oldTxt = txtNode.nodeValue;

        for (var J = 0; J < numTerms; J++) {
            oldTxt = oldTxt.replace (replaceArry[J][0], replaceArry[J][1]);
        }
        txtNode.nodeValue = oldTxt;
    }
})();
